# Nombre del Workflow: se mostrará en la pestaña "Actions" de GitHub
# Nombre del Workflow
name: 02 - Student PR Quality Check

# 1. Evento (Trigger): Cuándo se debe ejecutar este workflow
on:
  pull_request:
    branches: [main, master] # Se ejecuta en PRs dirigidos a la rama main o master

# 2. Jobs: Lista de trabajos a ejecutar
jobs:
  # Nombre del trabajo (puedes llamarlo como quieras)
  test-and-lint:
    # 3. Runner: La máquina virtual donde se ejecutará el trabajo
    runs-on: ubuntu-latest

    # 4. Steps: Los pasos que se ejecutarán secuencialmente
    steps:
      # Paso 1: Descargar el código del repositorio (del PR)
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configurar el entorno de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Puedes especificar la versión que usas

      # Paso 3: Instalar dependencias (solo flake8)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      # Paso 4: Ejecutar Linting (revisa el estilo del código)
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
